### ISSUE TITLE
Update Resource Allocation for SSO instance and postgres

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#113]
## Summary

Based on the baseline metrics of what resources our pods consume during operational hours, adjust the resource request/limits for cpu and memory.

## Definition of Done
- new resource tested in lower environments
- postgres resources adjusted and deployed
- sso resources adjusted and deployed
- optional: automate off hour maintenance task (via cornjob and a playbook?)

### Updates:
As we have had several service degradation on prod sso recently, this might be something we want to do asap.
Suggestion from redhat: `I suggest going to 1 core request and 2 core limit. For memory, go with 2g request and limit. This will give 1g to the container and 1g to the heap.`

**Comment by ShellyXueHan** [comment]
### Some thoughts to start with down the resource tuning journey:

let's assume average resource consumption is X (both memory and CPU historic statistic from baseline).

**For SSO pods**, we want to set `resource request` to be on the average usage; while resource limit set a bit higher that avg is only 80% of it (cuz it's also 80% threshold that triggers HPA)
- resource request = X
- resource limit = 1.25X

**For DB pods**, because the load does not get spread among the pods, it's better to have more space to grow.
- resource request = X
- resource limit = 2X

**Comment by patricksimonian** [comment]
@ShellyXueHan did you change the resources?

**Comment by ShellyXueHan** [comment]
not yet, still at the collection stage. Just some thinking there in case I forgot later on. I feel that we still need more testing to decide on where to start with. So far we've got some baseline figures: https://github.com/bcgov/ocp-sso/wiki/Operational-Profiling#results and let's sync up with redhat when making the decision.
