### ISSUE TITLE
oidc.gov.bc.ca SSL Cert update

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#190]
**Describe the issue**
SSL Cert for `oidc.gov.bc.ca` is expiring in a month. Let's get an iStore order in place and update it.

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done
- [ ] istore order created
- [ ] tech contact updated
- [ ] ssl cert updated and installed

**Comment by ConradBoydElliottGustafson** [comment]
@brycereid73 Looks like this needs to be groomed and prioritized -- just making sure you see it in the backlog.

**Comment by brycereid73** [comment]
@ShellyXueHan Shelly, I have an IDIR now and I can submit a ServiceNow ticket and they'll create an iStore ticket for me. 

I roughly know what the URL is used for, but could you provide a small description of what it is and why it's important? I think it'll help ensure we get the SSL cert renewed without too much hassle. 
thx!! Bryce

**Comment by ShellyXueHan** [comment]
The SSL Cert for oidc.gov.bc.ca is expiring at Saturday, April 3, 2021 at 10:58:00 AM Pacific. That's the URL for production SSO service, so it's important.... not sure if that explains it?

The cert is renewed every year, so it's better to point the contact list to Conrad or Niran.

Once you get the updated SSL cert, the team can then install it on the SSO route.

**Comment by brycereid73** [comment]
I've submitted a ticket in ServiceNow. Once I get the ticket/response, I'll provide an update.

**Comment by ConradBoydElliottGustafson** [comment]
@brycereid73 Please point the contact list to yourself or another dedicated team member. I'm 50% so it's better to leave me off critical path if it can be avoided. Thanks!

**Comment by brycereid73** [comment]
@nvunnamm @ConradBoydElliottGustafson 
Hi Guys, we need a CSR in order to complete the iStore request. 

The following are the instructions for getting a CSR from non-IIS servers. 
https://www.entrust.com/knowledgebase/ssl/ssl-tls-certificate-installation-help

##For future reference, here are the instructions and FAQs. 
[Ordering Process and Best Practices for the Issuance of Trusted
SSL Certificates](https://app.zenhub.com/files/104518313/43e05e2f-6253-4516-94bb-f9c5a36f69f9/download)

[SSL Certificates FAQ](https://app.zenhub.com/files/104518313/b8d5c675-1c84-499b-bc5f-f449f796753d/download)

**Comment by nvunnamm** [comment]
@brycereid73 I have attached the csr and key in email.

**Comment by brycereid73** [comment]
I've sent an email to IMB with the CSR and key. 

I have an IMB ticket, not an iStore ticket yet. 
http://imbsd.gov.bc.ca/Ticket/60652
