### ISSUE TITLE
Staff Name change causes Error 500 when signing into keycloak

### ISSUE THREAD

**Issue by gil0109** [bcgov/ocp-sso#29]
When an IDIR employee requests a name change, the IDIR ID is changed.  When the staff logs into an application using keycloak with the new IDIR ID, they receive an internal error message.

The error in DevTools is: POST https://sso.pathfinder.gov.bc.ca/auth/realms/idir/broker/idir/endpoint 500 (Internal Server Error)

Note: Changing the name itself is not a problem, it breaks because the username changed.

**Comment by cvarjao** [comment]
Workaround: Since the user ends up with multiple accounts in Keycloak, the previous user account needs to be `deactivate`, and its `Identity Provider Link` removed.

**Comment by NickPhura** [comment]
This appears to be the exact issue one of our ACRFD users is currently experiencing.
They had a name/username change and have never been able to log in since, and it is affecting their ability to do their job.

We deleted their keycloak user entirely, in the hopes that the new one would be created, but their new IDIR never appears in keycloak, and so they continue to experience this issue. 

User: Kristie Earl (né Bowerman)
Old IDIR: kbowerma
New IDIR: kearl

**Comment by ShellyXueHan** [comment]
Update: to remove the duplicated user in KeyCloak, please request here: https://github.com/BCDevOps/devops-requests with the type `Request to remove a user from KeyCloak`.

**Comment by zsamji** [comment]
Closing as no additional scenarios raised in the last few months
